<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends Front_end{
    function __construct()
    {
        parent::__construct();
    
        $this->load->model('Tag_model');
        $this->load->model('Book_tag_model');
        $this->load->library('upload');
        $this->load->model('Section_model');
          $this->load->model('Book_model');
    }

    function index()
    {
        
       $data['book'] = $this->Book_model->get_all_book();
        
               $data['book'] = $this->Book_model->get_all_book();
        $data['get_sub_section'] = $this->Section_model->get_sub_section();
        $this->layout->view('book/index',$data);
    }
}
