<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Section extends Front_end{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Section_model');
    } 

    /*
     * Listing of section
     */
    function index()
    {
        $data['section'] = $this->Section_model->get_all_section();
        
        $this->layout->view('section/index',$data);
    }

    /*
     * Adding a new section
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'section_name' => $this->input->post('section_name'),
				'parent_id' => $this->input->post('section_name_select'),
				
            );
            
            $section_id = $this->Section_model->add_section($params);
            redirect('section/index');
        }
        else
        {            
           $data['get_all_section']=$this->Section_model->get_all_section();
             $this->layout->view('section/add',$data);
        }
    }  

    /*
     * Editing a section
     */
    function edit($section_id)
    {   
        // check if the section exists before trying to edit it
        $data['section'] = $this->Section_model->get_section($section_id);
        
        if(isset($data['section']['section_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
				'section_name' => $this->input->post('section_name'),
				'parent_id' => $this->input->post('section_name_select'),
				
            );

                $this->Section_model->update_section($section_id,$params);            
                redirect('section/index');
            }
            else
            {
              $data['get_all_section']=$this->Section_model->get_all_section();
               $this->layout->view('section/edit',$data);
            }
        }
        else
            show_error('The section you are trying to edit does not exist.');
    } 

    /*
     * Deleting section
     */
    function remove($section_id)
    {
        $section = $this->Section_model->get_section($section_id);

        // check if the section exists before trying to delete it
        if(isset($section['section_id']))
        {
            $this->Section_model->delete_section($section_id);
            redirect('section/index');
        }
        else
            show_error('The section you are trying to delete does not exist.');
    }
    
}
