<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Test extends Front_end{
    function __construct()
    {
        parent::__construct();
       
    } 

    /*
     * Listing of tag
     */
    function index()
    {
       if(isset($_POST["skill"]))
{
// $connect = new PDO("mysql:host=localhost;dbname=testing", "root", "");
// $query = "INSERT INTO programmer(name, skill) VALUES(:name, :skill)";
// $statement = $connect->prepare($query);
// $statement->execute(
//  array(
//   ':name'  => $_POST["name"],
//   ':skill' => $_POST["skill"]
//  )
// );
// $result = $statement->fetchAll();
// $output = '';
// if(isset($result))
// {
//  $output = '
//  <div class="alert alert-success">
//   Your data has been successfully saved into System
//  </div>
//  ';
// }
// echo $output;
           echo $_POST["skill"];
}

    }
	function test_view(){
		
		$this->layout->view("tag/tag_view_d");
	}
	
	

    
}
