<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Book_tag_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get book_tag by book_tag_id
     */
    function get_book_tag($book_tag_id)
    {
        return $this->db->get_where('book_tag',array('book_tag_id'=>$book_tag_id))->row_array();
    }
    
    /*
     * Get all book_tag count
     */
    function get_all_book_tag_count()
    {
        $this->db->from('book_tag');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all book_tag
     */
    function get_all_book_tag($params = array())
    {
        $this->db->order_by('book_tag_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('book_tag')->result_array();
    }
        
    /*
     * function to add new book_tag
     */
    function add_book_tag($params)
    {
        $this->db->insert('book_tag',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update book_tag
     */
    function update_book_tag($book_tag_id,$params)
    {
        $this->db->where('book_tag_id',$book_tag_id);
        return $this->db->update('book_tag',$params);
    }
    
    /*
     * function to delete book_tag
     */
    function delete_book_tag($book_tag_id)
    {
        return $this->db->delete('book_tag',array('book_tag_id'=>$book_tag_id));
    }
}
