<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Book_model extends CI_Model {

    function __construct() {
        parent::__construct();
    }

    /*
     * Get book by book_id
     */

    function get_book($book_id) {
        return $this->db->get_where('book', array('book_id' => $book_id))->row_array();
    }

    /*
     * Get all book
     */

    function get_all_book() {
        $this->db->order_by('book_id', 'desc');
        return $this->db->get('book')->result_array();
    }

    /*
     * function to add new book
     */

    function add_book($params) {
        $this->db->insert('book', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update book
     */

    function update_book($book_id, $params) {
        $this->db->where('book_id', $book_id);
        return $this->db->update('book', $params);
    }

    /*
     * function to delete book
     */

    function delete_book($book_id) {


        //  return $this->db->delete('book',array('book_id'=>$book_id));
        // $sql = "delete from book ,book_tag  using book,  book_tag where (book.book_id=book_tag.book_id)  and (book.book_id='".$book_id."' )";




        $sql2 = "delete from tag using tag where tag_id in (select tag_id from book_tag where book_id='" . $book_id . "') and tag_id NOT IN "
                . "(SELECT tag_id FROM book_tag WHERE book_id != '" . $book_id . "')";
        $this->db->query($sql2);
        $sql1 = "delete from book,book_tag using book,book_tag where  book.book_id=book_tag.book_id and book.book_id='" . $book_id . "' ";
        $this->db->query($sql1);
    }

    function search_via_section_k($section_id) {


        $sql = "select * from tag,book_tag,book where  book.book_id=book_tag.book_id and book_tag.tag_id=tag.tag_id and book.section_id='" . $section_id . "'";


        $query = $this->db->query($sql);

        return $query->row();
    }

    function search_via_section($section_id) {


        $sql = "select * from book where book.file IS NOT NULL and   section_id='" . $section_id . "' ";


        $query = $this->db->query($sql);

        return $query->result();
    }
     function search_via_section_to_edit($section_id) {


        $sql = "select * from book where   section_id='" . $section_id . "'";


        $query = $this->db->query($sql);

        return $query->result_array();
    }

    function get_tag_book($book_id) {
        $sql = "select * from tag,book_tag,book where book.book_id=book_tag.book_id and book_tag.tag_id=tag.tag_id and book.book_id='" . $book_id . "' ";
        $query = $this->db->query($sql);
        return $query->row();
    }

//      function get_tag_book_via_section($section_id) {
//        $sql = "select * from tag,book_tag,book where book.book_id=book_tag.book_id and book_tag.tag_id=tag.tag_id and book.section_id='" . $section_id . "' ";
//        $query = $this->db->query($sql);
//       return $query->result();
//    }


    function search_material_book_via_section($section_id) {
        $sql = "select * from book,materials where book.section_id='" . $section_id . "' and book.book_id=materials.book_id ";
        $query = $this->db->query($sql);
        return $query->result();
    }

    public function getbooksCount($section_id) {

        $sql = "select count(book.section_id) as allcount from book where   section_id='" . $section_id . "'";

        $query = $this->db->query($sql);

        $result = $query->result_array();
        if ($result) {

            return $result[0]['allcount'];
        } else {
            return false;
        }
    }

    public function books($rowno, $rowperpage, $section_id) {

        $this->db->select('*');
        $this->db->from('book b ,materials m');
        $this->db->where('(b.section_id="' . $section_id . '") and (b.book_id=m.book_id) ');
        $this->db->limit($rowperpage, $rowno);
        $query = $this->db->get();
        if ($query) {

            return $query->result_array();
        } else {
            return false;
        }
    }
    function getgeneration() {
        $sql="BEGIN
    DECLARE rv VARCHAR(1024);
    DECLARE cm CHAR(1);
    DECLARE ch INT;

    SET rv = '';
    SET cm = '';
    SET ch = GivenID;
    WHILE ch > 0 DO
        SELECT IFNULL(parent_id,-1) INTO ch FROM
        (SELECT parent_id FROM section WHERE section_id = ch) A;
        IF ch > 0 THEN
            SET rv = CONCAT(rv,cm,ch);
            SET cm = ',';
        END IF;
    END WHILE;
    RETURN rv;
END";
        
    }
    
  
    
    

}
