<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Field_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get field by field_id
     */
    function get_field($field_id)
    {
        return $this->db->get_where('fields',array('field_id'=>$field_id))->row_array();
    }
        
    /*
     * Get all field
     */
    function get_all_field()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('custom_fields')->result_array();
    }
        
    /*
     * function to add new field
     */
    function add_field($params)
    {
        $this->db->insert('fields_values',$params);
        return $this->db->insert_id();
    }
    
        function add_custom_field($params)
    {
        $this->db->insert('custom_fields',$params);
        return $this->db->insert_id();
    }
    
    
    
    
    
    /*
     * function to update field
     */
    function update_field($field_id,$book_id,$params)
    {
        $this->db->where('field_id',$field_id);
         $this->db->where('book_id',$book_id);
        return $this->db->update('fields_values',$params);
    }
    
//    function update_field_() {
//        $sql='UPDATE suppliers
//SET 
//supplier_name = "TBD" WHERE city = "Redwood City" AND supplier_id <> 900;';
//
//
//    }
    

      
   
  
    
    function get_tag_field($field_id) {
        $sql="select * from tag,field_tag,field where field.field_id=field_tag.field_id and field_tag.tag_id=tag.tag_id and field.field_id='".$field_id."' ";
          $query = $this->db->query($sql);
        return $query->row();
    }
    function get_field_book($book_id)
    {
        return $this->db->get_where('fields',array('book_id'=>$book_id))->result_array();
    }
    
    function delete_field($book_id) {

        $sql1 = "delete from fields using fields where  fields.book_id='" . $book_id . "' ";
        $this->db->query($sql1);
    }
    
    function get_custom_fields() {
        $data = $this->db->query("select * from custom_fields ")->result_array();
        return $data;
    }
	
	/* function get_field_book(){
		
		$data = $this->db->query("select * from custom_fields a,fields_values b where  ")->result_array();
	} */
 
}
