<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Material_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get material by material_id
     */
    function get_material($material_id)
    {
        return $this->db->get_where('materials',array('material_id'=>$material_id))->row_array();
    }
        
    /*
     * Get all material
     */
    function get_all_material()
    {
        $this->db->order_by('material_id', 'desc');
        return $this->db->get('materials')->result_array();
    }
        
    /*
     * function to add new material
     */
    function add_material($params)
    {
        $this->db->insert('materials',$params);
        return $this->db->insert_id();
    }
    
    
    /*
     * function to update material
     */
    function update_material($material_id,$params)
    {
        $this->db->where('material_id',$material_id);
        return $this->db->update('materials',$params);
    }
   
    
          function update_material_book($book_id,$params)
    {
           $this->db->where('book_id', $book_id);
        return $this->db->update('materials', $params);
    }
  
    
    function get_tag_material($material_id) {
        $sql="select * from tag,material_tag,material where material.material_id=material_tag.material_id and material_tag.tag_id=tag.tag_id and material.material_id='".$material_id."' ";
          $query = $this->db->query($sql);
        return $query->row();
    }
    function get_material_book($book_id)
    {
        return $this->db->get_where('materials',array('material_id'=>$material_id))->row_array();
    }
    
    function delete_material($book_id) {





        
        $sql1 = "delete from materials using materials where  materials.book_id='" . $book_id . "' ";
        $this->db->query($sql1);
    }
 
}
