<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Version_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get version by version_id
     */
    function get_version($version_id)
    {
        return $this->db->get_where('version',array('version_id'=>$version_id))->row_array();
    }
        
    /*
     * Get all version
     */
    function get_all_version()
    {
        $this->db->order_by('version_id', 'desc');
        return $this->db->get('version')->result_array();
    }
        
    /*
     * function to add new version
     */
    function add_version($params)
    {
        $this->db->insert('version',$params);
        return $this->db->insert_id();
    }
    
    
    /*
     * function to update version
     */
    function update_version($version_id,$params)
    {
        $this->db->where('version_id',$version_id);
        return $this->db->update('version',$params);
    }
   
    
          function update_version_book($version_id,$params)
    {
           $this->db->where('version_id', $version_id);
        return $this->db->update('version', $params);
    }
          function update_version_book_contracts($book_id,$params)
    {
           $this->db->where('book_id', $book_id);
        return $this->db->update('version', $params);
    }
  
    
    function get_tag_version($version_id) {
        $sql="select * from tag,version_tag,version where version.version_id=version_tag.version_id and version_tag.tag_id=tag.tag_id and version.version_id='".$version_id."' ";
          $query = $this->db->query($sql);
        return $query->row();
    }
    function get_version_book($book_id)
    {
        return $this->db->get_where('version',array('book_id'=>$book_id))->result_array();
    }
    
    function delete_version($book_id) {

        $sql1 = "delete from version using version where  version.book_id='" . $book_id . "' ";
        $this->db->query($sql1);
    }
 
}
